---
- name: all iws servers global configuration.
  hosts: iwss
  #hosts: iws-dnss
  gather_facts: no
  tasks:

  - name: change yum.conf for kernel and os not update.
    lineinfile:
      name: /etc/yum.conf
      regexp: '^exclude=kernel'
      line: 'exclude=kernel* centos*'
      state: present

  - name: add nameserver.
    lineinfile:
      name: /etc/resolv.conf
      regexp: '^nameserver 8\.8\.*'
      line: 'nameserver 8.8.4.4'
      state: present

  #- name: chage state disabled for selinux.
  #  lineinfile:
  #    name: /etc/selinux/config
  #    regexp: '^SELINUX='
  #    line: 'SELINUX=disabled'

  #- name: update pamd.
  #  pamd:

  - name: yum update all package.
    yum: name='*' state=latest

  - name: install the "Base" package group.
    yum: name='@Base' state=present

  - name: yum install package.
    yum: name={{ item }} state=latest
    with_items:
      - nmap
      - ftp
      - telnet
      - epel-release

  - name: install tripwire.
    yum: name=tripwire state=latest

  #- name: install libselinux-python.
  #  yum: name=libselinux-python state=present

  - name: stop services.
    service: name={{ item }} state=stopped enabled=no
    with_items:
      - acpid
      - cpuspeed
      - haldaemon
      - ip6tables
      - iscsi
      - iscsid
      - mdmonitor
      - messagebus
      - netfs
      - postfix

  - name: disable ipv6.
    sysctl: |
      name={{ item }}
      value=1
      sysctl_set=yes
      sysctl_file=/etc/sysctl.d/ipv6.conf
    with_items:
      - net.ipv6.conf.all.disable_ipv6
      - net.ipv6.conf.default.disable_ipv6

- name: task dns servers.
  hosts: iws-dnss
  gather_facts: no
  tasks:

  - name: install yum-plugin.
    yum: name={{ item }} state=latest
    with_items:
      - yum-plugin-priorities

  - name: get repository for pdns.
    get_url:
      url: https://repo.powerdns.com/repo-files/centos-auth-40.repo
      dest: /etc/yum.repos.d/powerdns-auth-40.repo

  - name: pdns install
    yum: name=pdns-4.0.3 state=present
#
#  - name: pdns process start with enable
#    service: name=pdns state=started enabled=yes
#
#- name: db tasks
#  hosts: db-servers
#  connection: docker
#  gather_facts: no
#  tasks:
#
#  - name: mysqld install
#    yum: name=mysql-server state=latest
#
#  - name: mysqld process start with enable
#    service: name=mysqld state=started enabled=yes
