- hosts: targets
  user: root
  tasks:
  - name: install nginx
    yum: name=nginx state=latest
    notify: restart nginx

  - name: install mysql
    yum: name=mysql-server state=latest
    notify: restart mysql

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted

    - name: restart mysqld
      service: name=mysqld state=restarted
